//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopHardware.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Title { get; set; }
        public int Price { get; set; }
        public string ImagePath { get; set; }
        public string Descripton { get; set; }
    
        public virtual Category CategoryOfProduct { get; set; }
    }
}
